{{ if .Values.web.primaryDatabaseDeployment }}
{{ if .Values.web.primaryDatabaseDeployment.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
  name: {{ include "mastodon.fullname" . }}-web-primary-db
spec:
  ports:
    - name: http
      port: 3000
      targetPort: http
  selector:
    app.kubernetes.io/component: web-primary-db-only
    {{- include "mastodon.selectorLabels" . | nindent 4 }}
{{ end }}
{{ end }}
