# Creates a secret with the name: {{ include "asonix.fullname" . }}-secrets-env
# Contents:
# - API_TOKEN
# - TELEGRAM_TOKEN
# - TELEGRAM_ADMIN_HANDLE
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "asonix.fullname" . }}-secret-env
  labels:
    {{- include "asonix.labels" . | nindent 4 }}
spec:
  itemPath: {{ .Values.onePassword.itemPath }}
