apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "asonix.fullname" . }}-pvc
  labels:
      {{- include "asonix.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
