apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "haproxy.fullname" . }}-config
  labels:
    {{- include "haproxy.labels" . | nindent 4 }}
data:
  haproxy.cfg: |
    global
      log stdout format raw local0

    defaults
     log global
     timeout connect 5s
     timeout client 1m
     timeout server 1m

    # https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#5.3
    resolvers kube-dns
      parse-resolv-conf
      resolve_retries    30
      timeout retry      1s
      hold valid         1s

    frontend redis
      bind :6379
      default_backend upstream_redis

    frontend stats
      mode http
      bind *:8404
      http-request use-service prometheus-exporter if { path /metrics }
      stats enable
      stats uri /stats
      stats refresh 10s

    backend upstream_redis
      server upstream_redis {{ .Values.upstreamRedis.host }}:{{ .Values.upstreamRedis.port }} ssl verify none check inter 1s resolvers kube-dns
