apiVersion: v1
kind: Service
metadata:
  name: {{ include "haproxy.fullname" . }}
  labels:
    {{- include "haproxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    {{- include "haproxy.selectorLabels" . | nindent 4 }}
