apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  destination:
    namespace: haproxy
    server: https://kubernetes.default.svc
  project: mastodon
  source:
    helm:
      valueFiles:
        - values.yaml
    path: haproxy-chart
    repoURL: git@github.com:toot-community/kubernetes.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
