apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  namespace: libretranslate
spec:
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 15Gi
  accessModes:
    - ReadWriteOnce
