apiVersion: v1
kind: Service
metadata:
  name: translate
  namespace: libretranslate
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: libretranslate
