apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.toot.community
  accounts.admin.enabled: "false"
  resource.exclusions: |
    - apiGroups:
        - cilium.io
      kinds:
        - CiliumIdentity
      clusters:
        - "*"
    - apiGroups:
        - velero.io
      kinds:
        - Backup
      clusters:
        - "*"
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: 1903db926fddef4367d7
          clientSecret: $dex.github.clientSecret
          orgs:
          - name: toot-community
